import {
  FaArrowLeft,
  FaArrowRight,
  FaCamera,
  FaCheck,
  FaChevronDown,
  FaCogs,
  FaCopy,
  FaDiscord,
  FaGripVertical,
  FaLink,
  FaPlus,
  FaTelegramPlane,
  FaTrash,
  FaTwitter,
  FaUser,
  FaUserAlt,
  FaWallet,
} from 'react-icons/fa';
import { MdCampaign, MdReviews } from 'react-icons/md';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  Add: FaPlus,
  ArrowRight: FaArrowRight,
  ArrowLeft: FaArrowLeft,
  Cogs: FaCogs,
  Copy: FaCopy,
  ChevronDown: FaChevronDown,
  Camera: FaCamera,
  Check: FaCheck,
  Wallet: FaWallet,
  Discord: FaDiscord,
  Twitter: FaTwitter,
  Telegram: FaTelegramPlane,
  GripVertical: FaGripVertical,
  Trash: FaTrash,
  User: FaUser,
  Link: FaLink,
  Review: MdReviews,
  Campaign: MdCampaign,
};
